language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - go build -v -o $HOME/gopath/src/github.com/damonchen/gb2260/cmd/generate github.com/damonchen/gb2260/cmd

script: cd ./cmd && ./generate && cd ../ && go test -v ./...